#pragma once
#include <WinSock2.h>
#include <iostream>
#include <d3d9.h>
#include <Psapi.h>
#include <deque>
#include <cmath>
#include <Windows.h>
#include <algorithm>
#include <string>
#include <climits>
#include <vector>
#include <d3dx9.h>
#include <stdio.h>
#include <memory>
#include <string>
#include <functional>
#include <iostream>
#include <optional>